language: python

python:
  - 3.5

env:
  global:
    - DJANGO="1.9.5"

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO

script:
  # - python manage.py makemigrations sajt
  # - python manage.py migrate sajt
  - python manage.py test sajt

branches:
  only:
    - master
    - develop

notifications:
  slack: lugozr:S7LA2ies5KxkaVCObexdB1Es